package cli_test

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"

	"github.com/Obedience-Corp/festival-installer/internal/cli"
)

func newGendocsRoot() *cobra.Command {
	root := &cobra.Command{Use: "festival", SilenceErrors: true, SilenceUsage: true}
	root.AddCommand(cli.NewVersionCommand(testFestivalVersion))
	root.AddCommand(cli.NewWhichCommand())
	root.AddCommand(cli.NewGendocsCommand())
	return root
}

func runGendocs(t *testing.T, args ...string) (string, string, error) {
	t.Helper()
	root := newGendocsRoot()
	var out, errOut bytes.Buffer
	root.SetOut(&out)
	root.SetErr(&errOut)
	root.SetArgs(append([]string{"gendocs"}, args...))
	err := root.Execute()
	return out.String(), errOut.String(), err
}

func TestGendocs_Markdown(t *testing.T) {
	outDir := t.TempDir()

	_, _, err := runGendocs(t, "--output", outDir, "--format", "markdown")
	if err != nil {
		t.Fatalf("gendocs markdown: %v", err)
	}

	wantFiles := []string{"festival.md", "festival_version.md", "festival_which.md"}
	for _, name := range wantFiles {
		path := filepath.Join(outDir, name)
		if _, err := os.Stat(path); err != nil {
			t.Fatalf("expected generated file %s: %v", name, err)
		}
	}

	data, err := os.ReadFile(filepath.Join(outDir, "festival_version.md"))
	if err != nil {
		t.Fatalf("read festival_version.md: %v", err)
	}
	content := string(data)

	if strings.Contains(content, "Auto generated by spf13/cobra") {
		t.Fatalf("expected no AutoGenTag footer, got:\n%s", content)
	}

	if strings.HasSuffix(content, "\n\n") {
		t.Fatalf("expected no trailing blank line, got trailing bytes %q", content[len(content)-10:])
	}
	if !strings.HasSuffix(content, "\n") {
		t.Fatalf("expected file to end with exactly one newline, got %q", content[len(content)-10:])
	}
}

func TestGendocs_Yaml(t *testing.T) {
	outDir := t.TempDir()

	_, _, err := runGendocs(t, "--output", outDir, "--format", "yaml")
	if err != nil {
		t.Fatalf("gendocs yaml: %v", err)
	}

	path := filepath.Join(outDir, "festival_version.yaml")
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("expected generated file festival_version.yaml: %v", err)
	}
}

func TestGendocs_RemovesStaleFiles(t *testing.T) {
	outDir := t.TempDir()

	stale := filepath.Join(outDir, "festival_removed-command.md")
	if err := os.WriteFile(stale, []byte("stale\n"), 0o644); err != nil {
		t.Fatalf("write stale file: %v", err)
	}

	_, _, err := runGendocs(t, "--output", outDir, "--format", "markdown")
	if err != nil {
		t.Fatalf("gendocs markdown: %v", err)
	}

	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Fatalf("expected stale generated file to be removed, stat err = %v", err)
	}
}

func TestGendocs_HiddenFromHelp(t *testing.T) {
	root := newGendocsRoot()
	var out bytes.Buffer
	root.SetOut(&out)
	root.SetArgs([]string{"--help"})
	if err := root.Execute(); err != nil {
		t.Fatalf("festival --help: %v", err)
	}
	if strings.Contains(out.String(), "gendocs") {
		t.Fatalf("expected gendocs to be hidden from help output, got:\n%s", out.String())
	}
}

func TestGendocs_DefaultOutputDir(t *testing.T) {
	cwd, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	t.Cleanup(func() {
		if err := os.Chdir(cwd); err != nil {
			t.Fatalf("restore cwd: %v", err)
		}
	})
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatalf("chdir: %v", err)
	}

	if _, _, err := runGendocs(t); err != nil {
		t.Fatalf("gendocs with default flags: %v", err)
	}

	if _, err := os.Stat(filepath.Join("docs", "festival_version.md")); err != nil {
		t.Fatalf("expected default output dir docs/ to contain generated files: %v", err)
	}
}

func TestGendocs_UnknownFormat(t *testing.T) {
	outDir := t.TempDir()

	_, _, err := runGendocs(t, "--output", outDir, "--format", "bogus")
	if err == nil {
		t.Fatal("expected error for unknown format")
	}
	if !hasErrorCode(err, "E_GENDOCS_FORMAT") {
		t.Fatalf("expected E_GENDOCS_FORMAT, got: %v", err)
	}
}

func TestGendocs_RejectsExtraArgs(t *testing.T) {
	_, _, err := runGendocs(t, "extra-arg")
	if err == nil {
		t.Fatal("expected gendocs extra-arg to be rejected")
	}
}
